#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate the Employee level-segmented question import migration from Employee.xlsx.

Usage:
    python database/scripts/generate_employee_questions_sql.py "C:\\path\\Employee.xlsx"

Produces: database/migrations/029_employee_level_questions_import.sql

The workbook has 3 sheets (one per difficulty level), each with 2 sets of 40
bilingual situational-judgment questions and 4 options (a-d) each.

Mapping decisions:
  - sheet name -> assessment_questions.board  (Entry / Medium / Executive)
  - program    -> code = 'EMPLOYEE'
  - level      -> assessment_levels.level_number = 1
  - category   -> NULL (these are not DISC-trait questions)
  - options    -> disc_factor NULL, score_value 0, is_correct false
The whole batch is idempotent via metadata->>'source' = SOURCE_MARKER.
"""
import json
import os
import sys

import openpyxl

SOURCE_MARKER = "employee_xlsx_v1"

SHEET_TO_BOARD = {
    "Level 1": "Entry",
    "Level 2": "Medium",
    "Level 3": "Executive",
}

# Column order in every sheet (0-indexed).
COL = {
    "set": 0,
    "qnum": 1,
    "context_en": 2,
    "question_en": 3,
    "context_ta": 4,
    "question_ta": 5,
    "metadata": 6,
    "opt_en": [7, 8, 9, 10],   # a, b, c, d
    "opt_ta": [11, 12, 13, 14],
}

# Fixed DISC factor per option position: A->D, B->I, C->S, D->C. All score 1.
OPTION_DISC_FACTOR = ["D", "I", "S", "C"]
OPTION_SCORE_VALUE = 1


def sql_str(val):
    """Render a Python value as a SQL string literal or NULL."""
    if val is None:
        return "NULL"
    s = str(val).strip()
    if s == "":
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def to_int(val):
    if val is None or str(val).strip() == "":
        return None
    return int(float(val))


def parse_metadata(cell, board):
    meta = {}
    if cell is not None and str(cell).strip() != "":
        try:
            meta = json.loads(str(cell))
            if not isinstance(meta, dict):
                meta = {"raw": str(cell)}
        except (ValueError, TypeError):
            meta = {"raw": str(cell)}
    meta["board"] = board
    meta["source"] = SOURCE_MARKER
    return meta


def meta_literal(meta):
    # Compact, deterministic JSON; ensure_ascii=False keeps Tamil readable.
    return "'" + json.dumps(meta, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def main():
    if len(sys.argv) < 2:
        print("Usage: generate_employee_questions_sql.py <Employee.xlsx>")
        sys.exit(1)

    xlsx_path = sys.argv[1]
    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(
        here, "..", "migrations", "029_employee_level_questions_import.sql"
    )

    wb = openpyxl.load_workbook(xlsx_path, data_only=True)

    out = []
    out.append("-- ============================================================")
    out.append("-- Employee level-segmented main questions import (auto-generated)")
    out.append("-- Source: Employee.xlsx | Program: EMPLOYEE | Level: 1")
    out.append("-- Sheets -> board: Level 1=Entry, Level 2=Medium, Level 3=Executive")
    out.append("-- Options: A->D, B->I, C->S, D->C (disc_factor), score_value 1")
    out.append("-- 3 levels x 2 sets x 40 questions. marker: %s" % SOURCE_MARKER)
    out.append("-- Re-runnable: the preamble removes any prior rows with this marker.")
    out.append("-- Generated by database/scripts/generate_employee_questions_sql.py")
    out.append("-- ============================================================")
    out.append("BEGIN;")
    out.append("")
    out.append("-- Idempotency: clear any previous import of THIS batch (by source marker).")
    out.append("DELETE FROM assessment_question_options o")
    out.append(" USING assessment_questions q")
    out.append(" WHERE o.question_id = q.id AND q.metadata->>'source' = '%s';" % SOURCE_MARKER)
    out.append("DELETE FROM assessment_questions WHERE metadata->>'source' = '%s';" % SOURCE_MARKER)
    out.append("")

    total_q = 0
    total_o = 0

    for sheet in wb.worksheets:
        board = SHEET_TO_BOARD.get(sheet.title)
        if board is None:
            out.append("-- WARNING: unmapped sheet '%s' skipped" % sheet.title)
            continue

        out.append("-- ============================================================")
        out.append("-- Sheet '%s' -> board '%s'" % (sheet.title, board))
        out.append("-- ============================================================")

        rows = list(sheet.iter_rows(values_only=True))
        for r in rows[1:]:  # skip header
            if r is None or all(c is None or str(c).strip() == "" for c in r):
                continue
            set_no = to_int(r[COL["set"]])
            q_no = to_int(r[COL["qnum"]])
            if set_no is None:
                continue

            meta = parse_metadata(r[COL["metadata"]], board)
            external_code = "EMP-%s-S%s-Q%s" % (board[:3].upper(), set_no, q_no)

            out.append("-- %s Set %s Q%s" % (board, set_no, q_no))
            out.append("WITH q AS (")
            out.append("  INSERT INTO assessment_questions")
            out.append("    (assessment_level_id, set_number, program_id, board, external_code,")
            out.append("     context_text_en, question_text_en, context_text_ta, question_text_ta,")
            out.append("     metadata, is_active, is_deleted)")
            out.append("  VALUES ((SELECT id FROM assessment_levels WHERE level_number = 1), %d, "
                       "(SELECT id FROM programs WHERE code = 'EMPLOYEE'), %s, %s,"
                       % (set_no, sql_str(board), sql_str(external_code)))
            out.append("     %s, %s, %s, %s,"
                       % (sql_str(r[COL["context_en"]]), sql_str(r[COL["question_en"]]),
                          sql_str(r[COL["context_ta"]]), sql_str(r[COL["question_ta"]])))
            out.append("     %s, true, false)" % meta_literal(meta))
            out.append("  RETURNING id")
            out.append(")")
            out.append("INSERT INTO assessment_question_options")
            out.append("  (question_id, display_order, option_text_en, option_text_ta,")
            out.append("   disc_factor, score_value, is_correct, is_active, is_deleted)")
            out.append("SELECT q.id, v.ord, v.en, v.ta, v.fac, %d, false, true, false"
                       % OPTION_SCORE_VALUE)
            out.append("FROM q, (VALUES")
            opt_lines = []
            for i in range(4):
                en = r[COL["opt_en"][i]]
                ta = r[COL["opt_ta"][i]]
                fac = OPTION_DISC_FACTOR[i]
                opt_lines.append("  (%d, %s, %s, %s)"
                                 % (i + 1, sql_str(en), sql_str(ta), sql_str(fac)))
                total_o += 1
            out.append(",\n".join(opt_lines))
            out.append(") AS v(ord, en, ta, fac);")
            out.append("")
            total_q += 1

    out.append("COMMIT;")
    out.append("")
    out.append("-- Imported %d questions and %d options." % (total_q, total_o))

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    print("Wrote %s" % os.path.normpath(out_path))
    print("Questions: %d  Options: %d" % (total_q, total_o))


if __name__ == "__main__":
    main()
