
export interface CountryCode {
    name: string;
    code: string;
    dial_code: string;
    flag: string;
    maxLength: number; // Max digits excluding dial code
}

export const COUNTRY_CODES: CountryCode[] = [
    { name: "Afghanistan", code: "AF", dial_code: "+93", flag: "🇦🇫", maxLength: 9 },
    { name: "Albania", code: "AL", dial_code: "+355", flag: "🇦🇱", maxLength: 9 },
    { name: "Algeria", code: "DZ", dial_code: "+213", flag: "🇩🇿", maxLength: 9 },
    { name: "American Samoa", code: "AS", dial_code: "+1684", flag: "🇦🇸", maxLength: 7 },
    { name: "Andorra", code: "AD", dial_code: "+376", flag: "🇦🇩", maxLength: 6 },
    { name: "Angola", code: "AO", dial_code: "+244", flag: "🇦🇴", maxLength: 9 },
    { name: "Anguilla", code: "AI", dial_code: "+1264", flag: "🇦🇮", maxLength: 7 },
    { name: "Antigua and Barbuda", code: "AG", dial_code: "+1268", flag: "🇦🇬", maxLength: 7 },
    { name: "Argentina", code: "AR", dial_code: "+54", flag: "🇦🇷", maxLength: 10 },
    { name: "Armenia", code: "AM", dial_code: "+374", flag: "🇦🇲", maxLength: 8 },
    { name: "Aruba", code: "AW", dial_code: "+297", flag: "🇦🇼", maxLength: 7 },
    { name: "Australia", code: "AU", dial_code: "+61", flag: "🇦🇺", maxLength: 9 },
    { name: "Austria", code: "AT", dial_code: "+43", flag: "🇦🇹", maxLength: 13 },
    { name: "Azerbaijan", code: "AZ", dial_code: "+994", flag: "🇦🇿", maxLength: 9 },
    { name: "Bahamas", code: "BS", dial_code: "+1242", flag: "🇧🇸", maxLength: 7 },
    { name: "Bahrain", code: "BH", dial_code: "+973", flag: "🇧🇭", maxLength: 8 },
    { name: "Bangladesh", code: "BD", dial_code: "+880", flag: "🇧🇩", maxLength: 10 },
    { name: "Barbados", code: "BB", dial_code: "+1246", flag: "🇧🇧", maxLength: 7 },
    { name: "Belarus", code: "BY", dial_code: "+375", flag: "🇧🇾", maxLength: 9 },
    { name: "Belgium", code: "BE", dial_code: "+32", flag: "🇧🇪", maxLength: 9 },
    { name: "Belize", code: "BZ", dial_code: "+501", flag: "🇧🇿", maxLength: 7 },
    { name: "Benin", code: "BJ", dial_code: "+229", flag: "🇧🇯", maxLength: 8 },
    { name: "Bermuda", code: "BM", dial_code: "+1441", flag: "🇧🇲", maxLength: 7 },
    { name: "Bhutan", code: "BT", dial_code: "+975", flag: "🇧🇹", maxLength: 8 },
    { name: "Bolivia", code: "BO", dial_code: "+591", flag: "🇧🇴", maxLength: 8 },
    { name: "Bosnia and Herzegovina", code: "BA", dial_code: "+387", flag: "🇧🇦", maxLength: 8 },
    { name: "Botswana", code: "BW", dial_code: "+267", flag: "🇧🇼", maxLength: 8 },
    { name: "Brazil", code: "BR", dial_code: "+55", flag: "🇧🇷", maxLength: 11 },
    { name: "British Indian Ocean Territory", code: "IO", dial_code: "+246", flag: "🇮🇴", maxLength: 7 },
    { name: "Brunei Darussalam", code: "BN", dial_code: "+673", flag: "🇧🇳", maxLength: 7 },
    { name: "Bulgaria", code: "BG", dial_code: "+359", flag: "🇧🇬", maxLength: 9 },
    { name: "Burkina Faso", code: "BF", dial_code: "+226", flag: "🇧🇫", maxLength: 8 },
    { name: "Burundi", code: "BI", dial_code: "+257", flag: "🇧🇮", maxLength: 8 },
    { name: "Cambodia", code: "KH", dial_code: "+855", flag: "🇰🇭", maxLength: 9 },
    { name: "Cameroon", code: "CM", dial_code: "+237", flag: "🇨🇲", maxLength: 9 },
    { name: "Canada", code: "CA", dial_code: "+1", flag: "🇨🇦", maxLength: 10 },
    { name: "Cape Verde", code: "CV", dial_code: "+238", flag: "🇨🇻", maxLength: 7 },
    { name: "Cayman Islands", code: "KY", dial_code: "+1345", flag: "🇰🇾", maxLength: 7 },
    { name: "Central African Republic", code: "CF", dial_code: "+236", flag: "🇨🇫", maxLength: 8 },
    { name: "Chad", code: "TD", dial_code: "+235", flag: "🇹🇩", maxLength: 8 },
    { name: "Chile", code: "CL", dial_code: "+56", flag: "🇨🇱", maxLength: 9 },
    { name: "China", code: "CN", dial_code: "+86", flag: "🇨🇳", maxLength: 11 },
    { name: "Christmas Island", code: "CX", dial_code: "+61", flag: "🇨🇽", maxLength: 9 },
    { name: "Colombia", code: "CO", dial_code: "+57", flag: "🇨🇴", maxLength: 10 },
    { name: "Comoros", code: "KM", dial_code: "+269", flag: "🇰🇲", maxLength: 7 },
    { name: "Congo", code: "CG", dial_code: "+242", flag: "🇨🇬", maxLength: 9 },
    { name: "Congo, Democratic Republic", code: "CD", dial_code: "+243", flag: "🇨🇩", maxLength: 9 },
    { name: "Cook Islands", code: "CK", dial_code: "+682", flag: "🇨🇰", maxLength: 5 },
    { name: "Costa Rica", code: "CR", dial_code: "+506", flag: "🇨🇷", maxLength: 8 },
    { name: "Croatia", code: "HR", dial_code: "+385", flag: "🇭🇷", maxLength: 9 },
    { name: "Cuba", code: "CU", dial_code: "+53", flag: "🇨🇺", maxLength: 8 },
    { name: "Cyprus", code: "CY", dial_code: "+357", flag: "🇨🇾", maxLength: 8 },
    { name: "Czech Republic", code: "CZ", dial_code: "+420", flag: "🇨🇿", maxLength: 9 },
    { name: "Denmark", code: "DK", dial_code: "+45", flag: "🇩🇰", maxLength: 8 },
    { name: "Djibouti", code: "DJ", dial_code: "+253", flag: "🇩🇯", maxLength: 8 },
    { name: "Dominica", code: "DM", dial_code: "+1767", flag: "🇩🇲", maxLength: 7 },
    { name: "Dominican Republic", code: "DO", dial_code: "+1849", flag: "🇩🇴", maxLength: 10 },
    { name: "Ecuador", code: "EC", dial_code: "+593", flag: "🇪🇨", maxLength: 9 },
    { name: "Egypt", code: "EG", dial_code: "+20", flag: "🇪🇬", maxLength: 10 },
    { name: "El Salvador", code: "SV", dial_code: "+503", flag: "🇸🇻", maxLength: 8 },
    { name: "Equatorial Guinea", code: "GQ", dial_code: "+240", flag: "🇬🇶", maxLength: 9 },
    { name: "Eritrea", code: "ER", dial_code: "+291", flag: "🇪🇷", maxLength: 7 },
    { name: "Estonia", code: "EE", dial_code: "+372", flag: "🇪🇪", maxLength: 8 },
    { name: "Ethiopia", code: "ET", dial_code: "+251", flag: "🇪🇹", maxLength: 9 },
    { name: "Falkland Islands", code: "FK", dial_code: "+500", flag: "🇫🇰", maxLength: 5 },
    { name: "Faroe Islands", code: "FO", dial_code: "+298", flag: "🇫🇴", maxLength: 6 },
    { name: "Fiji", code: "FJ", dial_code: "+679", flag: "🇫🇯", maxLength: 7 },
    { name: "Finland", code: "FI", dial_code: "+358", flag: "🇫🇮", maxLength: 10 },
    { name: "France", code: "FR", dial_code: "+33", flag: "🇫🇷", maxLength: 9 },
    { name: "French Guiana", code: "GF", dial_code: "+594", flag: "🇬🇫", maxLength: 9 },
    { name: "French Polynesia", code: "PF", dial_code: "+689", flag: "🇵🇫", maxLength: 8 },
    { name: "Gabon", code: "GA", dial_code: "+241", flag: "🇬🇦", maxLength: 7 },
    { name: "Gambia", code: "GM", dial_code: "+220", flag: "🇬🇲", maxLength: 7 },
    { name: "Georgia", code: "GE", dial_code: "+995", flag: "🇬🇪", maxLength: 9 },
    { name: "Germany", code: "DE", dial_code: "+49", flag: "🇩🇪", maxLength: 11 },
    { name: "Ghana", code: "GH", dial_code: "+233", flag: "🇬🇭", maxLength: 9 },
    { name: "Gibraltar", code: "GI", dial_code: "+350", flag: "🇬🇮", maxLength: 8 },
    { name: "Greece", code: "GR", dial_code: "+30", flag: "🇬🇷", maxLength: 10 },
    { name: "Greenland", code: "GL", dial_code: "+299", flag: "🇬🇱", maxLength: 6 },
    { name: "Grenada", code: "GD", dial_code: "+1473", flag: "🇬🇩", maxLength: 7 },
    { name: "Guadeloupe", code: "GP", dial_code: "+590", flag: "🇬🇵", maxLength: 9 },
    { name: "Guam", code: "GU", dial_code: "+1671", flag: "🇬🇺", maxLength: 7 },
    { name: "Guatemala", code: "GT", dial_code: "+502", flag: "🇬🇹", maxLength: 8 },
    { name: "Guernsey", code: "GG", dial_code: "+44", flag: "🇬🇬", maxLength: 10 },
    { name: "Guinea", code: "GN", dial_code: "+224", flag: "🇬🇳", maxLength: 9 },
    { name: "Guinea-Bissau", code: "GW", dial_code: "+245", flag: "🇬🇼", maxLength: 7 },
    { name: "Guyana", code: "GY", dial_code: "+592", flag: "🇬🇾", maxLength: 7 },
    { name: "Haiti", code: "HT", dial_code: "+509", flag: "🇭🇹", maxLength: 8 },
    { name: "Honduras", code: "HN", dial_code: "+504", flag: "🇭🇳", maxLength: 8 },
    { name: "Hong Kong", code: "HK", dial_code: "+852", flag: "🇭🇰", maxLength: 8 },
    { name: "Hungary", code: "HU", dial_code: "+36", flag: "🇭🇺", maxLength: 9 },
    { name: "Iceland", code: "IS", dial_code: "+354", flag: "🇮🇸", maxLength: 7 },
    { name: "India", code: "IN", dial_code: "+91", flag: "🇮🇳", maxLength: 10 },
    { name: "Indonesia", code: "ID", dial_code: "+62", flag: "🇮🇩", maxLength: 12 },
    { name: "Iran", code: "IR", dial_code: "+98", flag: "🇮🇷", maxLength: 10 },
    { name: "Iraq", code: "IQ", dial_code: "+964", flag: "🇮🇶", maxLength: 10 },
    { name: "Ireland", code: "IE", dial_code: "+353", flag: "🇮🇪", maxLength: 9 },
    { name: "Isle of Man", code: "IM", dial_code: "+44", flag: "🇮🇲", maxLength: 10 },
    { name: "Israel", code: "IL", dial_code: "+972", flag: "🇮🇱", maxLength: 9 },
    { name: "Italy", code: "IT", dial_code: "+39", flag: "🇮🇹", maxLength: 10 },
    { name: "Jamaica", code: "JM", dial_code: "+1876", flag: "🇯🇲", maxLength: 7 },
    { name: "Japan", code: "JP", dial_code: "+81", flag: "🇯🇵", maxLength: 10 },
    { name: "Jersey", code: "JE", dial_code: "+44", flag: "🇯🇪", maxLength: 10 },
    { name: "Jordan", code: "JO", dial_code: "+962", flag: "🇯🇴", maxLength: 9 },
    { name: "Kazakhstan", code: "KZ", dial_code: "+7", flag: "🇰🇿", maxLength: 10 },
    { name: "Kenya", code: "KE", dial_code: "+254", flag: "🇰🇪", maxLength: 9 },
    { name: "Kiribati", code: "KI", dial_code: "+686", flag: "🇰🇮", maxLength: 5 },
    { name: "Korea, South", code: "KR", dial_code: "+82", flag: "🇰🇷", maxLength: 10 },
    { name: "Kuwait", code: "KW", dial_code: "+965", flag: "🇰🇼", maxLength: 8 },
    { name: "Kyrgyzstan", code: "KG", dial_code: "+996", flag: "🇰🇬", maxLength: 9 },
    { name: "Laos", code: "LA", dial_code: "+856", flag: "🇱🇦", maxLength: 9 },
    { name: "Latvia", code: "LV", dial_code: "+371", flag: "🇱🇻", maxLength: 8 },
    { name: "Lebanon", code: "LB", dial_code: "+961", flag: "🇱🇧", maxLength: 8 },
    { name: "Lesotho", code: "LS", dial_code: "+266", flag: "🇱🇸", maxLength: 8 },
    { name: "Liberia", code: "LR", dial_code: "+231", flag: "🇱🇷", maxLength: 7 },
    { name: "Libya", code: "LY", dial_code: "+218", flag: "🇱🇾", maxLength: 9 },
    { name: "Liechtenstein", code: "LI", dial_code: "+423", flag: "🇱🇮", maxLength: 7 },
    { name: "Lithuania", code: "LT", dial_code: "+370", flag: "🇱🇹", maxLength: 8 },
    { name: "Luxembourg", code: "LU", dial_code: "+352", flag: "🇱🇺", maxLength: 9 },
    { name: "Macau", code: "MO", dial_code: "+853", flag: "🇲🇴", maxLength: 8 },
    { name: "Madagascar", code: "MG", dial_code: "+261", flag: "🇲🇬", maxLength: 9 },
    { name: "Malawi", code: "MW", dial_code: "+265", flag: "🇲🇼", maxLength: 9 },
    { name: "Malaysia", code: "MY", dial_code: "+60", flag: "🇲🇾", maxLength: 10 },
    { name: "Maldives", code: "MV", dial_code: "+960", flag: "🇲🇻", maxLength: 7 },
    { name: "Mali", code: "ML", dial_code: "+223", flag: "🇲🇱", maxLength: 8 },
    { name: "Malta", code: "MT", dial_code: "+356", flag: "🇲🇹", maxLength: 8 },
    { name: "Marshall Islands", code: "MH", dial_code: "+692", flag: "🇲🇭", maxLength: 7 },
    { name: "Mauritania", code: "MR", dial_code: "+222", flag: "🇲🇷", maxLength: 8 },
    { name: "Mauritius", code: "MU", dial_code: "+230", flag: "🇲🇺", maxLength: 8 },
    { name: "Mexico", code: "MX", dial_code: "+52", flag: "🇲🇽", maxLength: 10 },
    { name: "Micronesia", code: "FM", dial_code: "+691", flag: "🇫🇲", maxLength: 7 },
    { name: "Moldova", code: "MD", dial_code: "+373", flag: "🇲🇩", maxLength: 8 },
    { name: "Monaco", code: "MC", dial_code: "+377", flag: "🇲🇨", maxLength: 8 },
    { name: "Mongolia", code: "MN", dial_code: "+976", flag: "🇲🇳", maxLength: 8 },
    { name: "Montenegro", code: "ME", dial_code: "+382", flag: "🇲🇪", maxLength: 8 },
    { name: "Montserrat", code: "MS", dial_code: "+1664", flag: "🇲🇸", maxLength: 7 },
    { name: "Morocco", code: "MA", dial_code: "+212", flag: "🇲🇦", maxLength: 9 },
    { name: "Mozambique", code: "MZ", dial_code: "+258", flag: "🇲🇿", maxLength: 9 },
    { name: "Myanmar", code: "MM", dial_code: "+95", flag: "🇲🇲", maxLength: 10 },
    { name: "Namibia", code: "NA", dial_code: "+264", flag: "🇳🇦", maxLength: 9 },
    { name: "Nauru", code: "NR", dial_code: "+674", flag: "🇳🇷", maxLength: 7 },
    { name: "Nepal", code: "NP", dial_code: "+977", flag: "🇳🇵", maxLength: 10 },
    { name: "Netherlands", code: "NL", dial_code: "+31", flag: "🇳🇱", maxLength: 9 },
    { name: "New Zealand", code: "NZ", dial_code: "+64", flag: "🇳🇿", maxLength: 9 },
    { name: "Nicaragua", code: "NI", dial_code: "+505", flag: "🇳🇮", maxLength: 8 },
    { name: "Niger", code: "NE", dial_code: "+227", flag: "🇳🇪", maxLength: 8 },
    { name: "Nigeria", code: "NG", dial_code: "+234", flag: "🇳🇬", maxLength: 10 },
    { name: "Niue", code: "NU", dial_code: "+683", flag: "🇳🇺", maxLength: 4 },
    { name: "Norfolk Island", code: "NF", dial_code: "+672", flag: "🇳🇫", maxLength: 6 },
    { name: "North Macedonia", code: "MK", dial_code: "+389", flag: "🇲🇰", maxLength: 8 },
    { name: "Norway", code: "NO", dial_code: "+47", flag: "🇳🇴", maxLength: 8 },
    { name: "Oman", code: "OM", dial_code: "+968", flag: "🇴🇲", maxLength: 8 },
    { name: "Pakistan", code: "PK", dial_code: "+92", flag: "🇵🇰", maxLength: 10 },
    { name: "Palau", code: "PW", dial_code: "+680", flag: "🇵🇼", maxLength: 7 },
    { name: "Panama", code: "PA", dial_code: "+507", flag: "🇵🇦", maxLength: 8 },
    { name: "Papua New Guinea", code: "PG", dial_code: "+675", flag: "🇵🇬", maxLength: 8 },
    { name: "Paraguay", code: "PY", dial_code: "+595", flag: "🇵🇾", maxLength: 9 },
    { name: "Peru", code: "PE", dial_code: "+51", flag: "🇵🇪", maxLength: 9 },
    { name: "Philippines", code: "PH", dial_code: "+63", flag: "🇵🇭", maxLength: 10 },
    { name: "Poland", code: "PL", dial_code: "+48", flag: "🇵🇱", maxLength: 9 },
    { name: "Portugal", code: "PT", dial_code: "+351", flag: "🇵🇹", maxLength: 9 },
    { name: "Puerto Rico", code: "PR", dial_code: "+1787", flag: "🇵🇷", maxLength: 7 },
    { name: "Qatar", code: "QA", dial_code: "+974", flag: "🇶🇦", maxLength: 8 },
    { name: "Romania", code: "RO", dial_code: "+40", flag: "🇷🇴", maxLength: 9 },
    { name: "Russia", code: "RU", dial_code: "+7", flag: "🇷🇺", maxLength: 10 },
    { name: "Rwanda", code: "RW", dial_code: "+250", flag: "🇷🇼", maxLength: 9 },
    { name: "Saint Kitts and Nevis", code: "KN", dial_code: "+1869", flag: "🇰🇳", maxLength: 7 },
    { name: "Saint Lucia", code: "LC", dial_code: "+1758", flag: "🇱🇨", maxLength: 7 },
    { name: "Samoa", code: "WS", dial_code: "+685", flag: "🇼🇸", maxLength: 7 },
    { name: "San Marino", code: "SM", dial_code: "+378", flag: "🇸🇲", maxLength: 10 },
    { name: "Saudi Arabia", code: "SA", dial_code: "+966", flag: "🇸🇦", maxLength: 9 },
    { name: "Senegal", code: "SN", dial_code: "+221", flag: "🇸🇳", maxLength: 9 },
    { name: "Serbia", code: "RS", dial_code: "+381", flag: "🇷🇸", maxLength: 9 },
    { name: "Seychelles", code: "SC", dial_code: "+248", flag: "🇸🇨", maxLength: 7 },
    { name: "Sierra Leone", code: "SL", dial_code: "+232", flag: "🇸🇱", maxLength: 8 },
    { name: "Singapore", code: "SG", dial_code: "+65", flag: "🇸🇬", maxLength: 8 },
    { name: "Slovakia", code: "SK", dial_code: "+421", flag: "🇸🇰", maxLength: 9 },
    { name: "Slovenia", code: "SI", dial_code: "+386", flag: "🇸🇮", maxLength: 8 },
    { name: "Solomon Islands", code: "SB", dial_code: "+677", flag: "🇸🇧", maxLength: 7 },
    { name: "Somalia", code: "SO", dial_code: "+252", flag: "🇸🇴", maxLength: 9 },
    { name: "South Africa", code: "ZA", dial_code: "+27", flag: "🇿🇦", maxLength: 9 },
    { name: "Spain", code: "ES", dial_code: "+34", flag: "🇪🇸", maxLength: 9 },
    { name: "Sri Lanka", code: "LK", dial_code: "+94", flag: "🇱🇰", maxLength: 9 },
    { name: "Sudan", code: "SD", dial_code: "+249", flag: "🇸🇩", maxLength: 9 },
    { name: "Sweden", code: "SE", dial_code: "+46", flag: "🇸🇪", maxLength: 9 },
    { name: "Switzerland", code: "CH", dial_code: "+41", flag: "🇨🇭", maxLength: 9 },
    { name: "Syria", code: "SY", dial_code: "+963", flag: "🇸🇾", maxLength: 9 },
    { name: "Taiwan", code: "TW", dial_code: "+886", flag: "🇹🇼", maxLength: 9 },
    { name: "Tajikistan", code: "TJ", dial_code: "+992", flag: "🇹🇯", maxLength: 9 },
    { name: "Tanzania", code: "TZ", dial_code: "+255", flag: "🇹🇿", maxLength: 9 },
    { name: "Thailand", code: "TH", dial_code: "+66", flag: "🇹🇭", maxLength: 9 },
    { name: "Togo", code: "TG", dial_code: "+228", flag: "🇹🇬", maxLength: 8 },
    { name: "Tonga", code: "TO", dial_code: "+676", flag: "🇹🇴", maxLength: 5 },
    { name: "Trinidad and Tobago", code: "TT", dial_code: "+1868", flag: "🇹🇹", maxLength: 7 },
    { name: "Tunisia", code: "TN", dial_code: "+216", flag: "🇹🇳", maxLength: 8 },
    { name: "Turkey", code: "TR", dial_code: "+90", flag: "🇹🇷", maxLength: 10 },
    { name: "Turkmenistan", code: "TM", dial_code: "+993", flag: "🇹🇲", maxLength: 8 },
    { name: "Tuvalu", code: "TV", dial_code: "+688", flag: "🇹🇻", maxLength: 5 },
    { name: "Uganda", code: "UG", dial_code: "+256", flag: "🇺🇬", maxLength: 9 },
    { name: "Ukraine", code: "UA", dial_code: "+380", flag: "🇺🇦", maxLength: 9 },
    { name: "United Arab Emirates", code: "AE", dial_code: "+971", flag: "🇦🇪", maxLength: 9 },
    { name: "United Kingdom", code: "GB", dial_code: "+44", flag: "🇬🇧", maxLength: 10 },
    { name: "United States", code: "US", dial_code: "+1", flag: "🇺🇸", maxLength: 10 },
    { name: "Uruguay", code: "UY", dial_code: "+598", flag: "🇺🇾", maxLength: 8 },
    { name: "Uzbekistan", code: "UZ", dial_code: "+998", flag: "🇺🇿", maxLength: 9 },
    { name: "Vanuatu", code: "VU", dial_code: "+678", flag: "🇻🇺", maxLength: 7 },
    { name: "Venezuela", code: "VE", dial_code: "+58", flag: "🇻🇪", maxLength: 10 },
    { name: "Vietnam", code: "VN", dial_code: "+84", flag: "🇻🇳", maxLength: 9 },
    { name: "Yemen", code: "YE", dial_code: "+967", flag: "🇾🇪", maxLength: 9 },
    { name: "Zambia", code: "ZM", dial_code: "+260", flag: "🇿🇲", maxLength: 9 },
    { name: "Zimbabwe", code: "ZW", dial_code: "+263", flag: "🇿🇼", maxLength: 9 }
];
